### ISSUE TITLE
Query API by pid

### ISSUE THREAD

**Issue by Olen** [slaxor505/OpenPlantbook-client#3]
Since I can not find a repo for the API-code itself, I am adding this here.

It should be possible to query the API using the "pid" of the plant (if it is unique, which I believe it is).

```
curl --request GET 'https://open.plantbook.io/api/v1/plant/detail/acer sieboldianum' \
--header 'Authorization: Bearer token_string'
```

**Comment by slaxor505** [comment]
Yes, this has been already developed and I will roll this out by this weekend. I will be exactly as you quoted.

`https://open.plantbook.io/api/v1/plant/detail/<pid-string>`

**Comment by slaxor505** [comment]
This has been rolled out in production. Please take a look at details in readme for release 1.0. Let me know if it any issues

**Comment by Olen** [comment]
Looks good.  Update the python demo client.

Closing this issue
