### ISSUE TITLE
Doubt on github logon

### ISSUE THREAD

**Issue by VincenzoMaletta** [slaxor505/OpenPlantbook-client#8]
Hello,
I've just created a new account to open.platbook.io, through Github autentication, and I noticed that the icon associated to my name (![plantbook icon](https://user-images.githubusercontent.com/12865597/127747268-814338bf-470c-4716-875d-036226fadb10.JPG)) do not match the one that I set in Github (![github icon](https://user-images.githubusercontent.com/12865597/127747229-4540efa5-b470-472d-983d-b05b8f5bd1e9.JPG))

I wonder if my subscription is connected to the right Github user account.

Also the "Settings" menù, under "Profile", does nothing; no profile setting page is opened.

Thank you for your kind assistance.

**Comment by slaxor505** [comment]
Hello,

The icon is not being used at the moment, it's the same default one for
every one which you can see. If it's your name then you are authenticated
correctly.

Regards,
Slava
